namespace AutoPost.Infrastructure;

internal static class Schema
{
    public const string Sql = """
CREATE TABLE "Events" ("Id" text PRIMARY KEY,"Source" text NOT NULL,"SourceId" text NOT NULL,"Title" text NOT NULL,"Body" text NOT NULL,"Url" text NOT NULL,"Category" text NOT NULL,"PublishedAt" bigint NOT NULL,"CollectedAt" bigint NOT NULL,"Demo" boolean NOT NULL,"Fingerprint" text NOT NULL,"GroupId" text NOT NULL,"AnalysisStatus" text NOT NULL);
CREATE UNIQUE INDEX ON "Events" ("Source","SourceId");
CREATE INDEX ON "Events" ("Demo","PublishedAt" DESC,"Id" DESC);
CREATE INDEX ON "Events" ("Fingerprint"); CREATE INDEX ON "Events" ("GroupId");
CREATE TABLE "Analyses" ("Id" text PRIMARY KEY,"EventId" text NOT NULL,"Result" text NOT NULL,"Model" text NOT NULL,"PromptVersion" text NOT NULL,"DurationMs" integer NOT NULL,"Usage" text NOT NULL,"CreatedAt" bigint NOT NULL);
CREATE UNIQUE INDEX ON "Analyses" ("EventId");
CREATE TABLE "Drafts" ("Id" text PRIMARY KEY,"Content" text NOT NULL,"Channels" text NOT NULL,"EventId" text,"Status" text NOT NULL,"Revision" integer NOT NULL,"ApprovedRevision" integer,"Demo" boolean NOT NULL,"Quarantined" boolean NOT NULL,"RuleId" text,"RuleVersion" integer,"CreatedAt" bigint NOT NULL,"UpdatedAt" bigint NOT NULL);
CREATE UNIQUE INDEX ON "Drafts" ("EventId","RuleId") WHERE "RuleId" IS NOT NULL;
CREATE TABLE "Versions" ("Id" text PRIMARY KEY,"DraftId" text NOT NULL,"Revision" integer NOT NULL,"Content" text NOT NULL,"Channels" text NOT NULL,"CreatedAt" bigint NOT NULL);
CREATE UNIQUE INDEX ON "Versions" ("DraftId","Revision");
CREATE TABLE "Deliveries" ("Id" text PRIMARY KEY,"DraftId" text NOT NULL,"Revision" integer NOT NULL,"Channel" text NOT NULL,"Account" text NOT NULL,"Status" text NOT NULL,"RemoteId" text,"Error" text,"RuleId" text,"RuleVersion" integer,"Attempts" integer NOT NULL,"CreatedAt" bigint NOT NULL,"UpdatedAt" bigint NOT NULL);
CREATE UNIQUE INDEX ON "Deliveries" ("DraftId","Revision","Channel"); CREATE INDEX ON "Deliveries" ("Channel","CreatedAt");
CREATE TABLE "Rules" ("Id" text PRIMARY KEY,"Name" text NOT NULL,"Enabled" boolean NOT NULL,"Version" integer NOT NULL,"Sources" text NOT NULL,"Keywords" text NOT NULL,"Channels" text NOT NULL,"Account" text NOT NULL,"DailyLimit" integer NOT NULL,"CooldownMinutes" integer NOT NULL,"StartHour" integer NOT NULL,"EndHour" integer NOT NULL);
CREATE TABLE "Sources" ("Id" text PRIMARY KEY,"Kind" text NOT NULL,"Name" text NOT NULL,"Address" text NOT NULL,"Enabled" boolean NOT NULL,"IntervalSeconds" integer NOT NULL,"NextRun" bigint NOT NULL,"Cursor" text NOT NULL,"PageToken" text NOT NULL,"PendingCursor" text NOT NULL,"Status" text NOT NULL,"Error" text,"LastSuccess" bigint);
CREATE TABLE "Jobs" ("Id" text PRIMARY KEY,"Kind" text NOT NULL,"Target" text NOT NULL,"Status" text NOT NULL,"DueAt" bigint NOT NULL,"LeaseUntil" bigint NOT NULL,"LeaseOwner" text,"Attempts" integer NOT NULL,"Error" text);
CREATE UNIQUE INDEX ON "Jobs" ("Kind","Target") WHERE "Status" IN ('pending','running'); CREATE INDEX ON "Jobs" ("Status","DueAt");
CREATE TABLE "Changes" ("Id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,"Kind" text NOT NULL,"Target" text NOT NULL,"CreatedAt" bigint NOT NULL);
CREATE TABLE "Audits" ("Id" text PRIMARY KEY,"Action" text NOT NULL,"Target" text NOT NULL,"Detail" text NOT NULL,"CreatedAt" bigint NOT NULL);
CREATE TABLE "Settings" ("Id" integer PRIMARY KEY,"AutoPaused" boolean NOT NULL,"AnalysisDailyLimit" integer NOT NULL,"ChannelDailyLimit" integer NOT NULL,"WorkerHeartbeat" bigint NOT NULL);
INSERT INTO "Settings" VALUES(1,true,100,20,0);
CREATE TABLE "Budgets" ("Id" text PRIMARY KEY,"Used" integer NOT NULL);
""";
}
