import {ModelPicker} from './ModelPicker';
import {useEffect,useRef,useState} from 'react';
import {useQuery,useQueryClient} from '@tanstack/react-query';
import * as Dialog from '@radix-ui/react-dialog';
import {ArrowUpRight,ArrowUp,History,Plus,Radio,Square,Sparkles,X} from 'lucide-react';
import {api,type EventItem} from './api';
import './agent.css';
type Session={id:string;title:string;updatedAt:number};
type Citation={id:string;title:string;url:string;source:string;publishedAt:number;collectedAt:number};
type Answer={summary?:string;facts?:string[];reports?:string[];predictions?:string[];rumors?:string[];uncertainties?:string[];sources?:Citation[];asOf?:number;draftId?:string;draft?:string};
type Message={id:string;prompt:string;status:string;progress:string;result:string;model:string;createdAt:number};
const active=(m:Message)=>['queued','running','waiting_quota'].includes(m.status);
const time=(stamp?:number)=>stamp?new Date(stamp*1000).toLocaleString('zh-CN',{hour12:false}):'时间未知';
export function AgentPanel({connected,event,onLogin,onDraft}:{connected:boolean;event:EventItem|null;onLogin:()=>void;onDraft:()=>void}) {
 const qc=useQueryClient(); const [open,setOpen]=useState(false),[history,setHistory]=useState(false),[id,setId]=useState(''),[prompt,setPrompt]=useState(''),[attach,setAttach]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState(''),[older,setOlder]=useState<Message[]>([]),[cursor,setCursor]=useState<string|null>(null);
 const [model,setModel]=useState('');
 const bottom=useRef<HTMLDivElement>(null);
 const status=useQuery({queryKey:['agent-status'],queryFn:()=>api('/agent/status'),enabled:connected&&open,refetchInterval:15000});
 const sessions=useQuery<Session[]>({queryKey:['agent-sessions'],queryFn:()=>api('/agent/sessions'),enabled:connected&&open});
 const messages=useQuery<{items:Message[];nextCursor:string|null}>({queryKey:['agent-messages',id],queryFn:()=>api('/agent/sessions/'+id+'/messages'),enabled:connected&&open&&!!id,refetchInterval:q=>q.state.data?.items.some(active)?1500:false});
 useEffect(()=>{setAttach(false)},[event?.id]);
 useEffect(()=>{bottom.current?.scrollIntoView({block:'nearest'})},[messages.data?.items.at(-1)?.status,messages.data?.items.length]);
 const current=messages.data?.items.find(active),rows=[...older,...(messages.data?.items??[])];
 async function send(action:string,text=prompt){if(!connected){onLogin();return}if(busy||current)return;setBusy(true);setError('');try{let session=id;if(!session){session=(await api<Session>('/agent/sessions','POST',{})).id;setId(session);setOlder([])}await api('/agent/sessions/'+session+'/messages','POST',{action,prompt:text,requestId:crypto.randomUUID(),eventId:attach&&event?event.id:null,model:model||null});setPrompt('');await qc.invalidateQueries({queryKey:['agent-messages',session]});await qc.invalidateQueries({queryKey:['agent-sessions']})}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 async function cancel(){if(!current)return;try{await api('/agent/tasks/'+current.id+'/cancel','POST',{});await qc.invalidateQueries({queryKey:['agent-messages',id]})}catch(e){setError((e as Error).message)}}
 function select(session:string){setId(session);setOlder([]);setCursor(null);setHistory(false);setError('')}
 async function loadOlder(){try{const page=await api<{items:Message[];nextCursor:string|null}>('/agent/sessions/'+id+'/messages?before='+encodeURIComponent(cursor??messages.data!.nextCursor!));setOlder(v=>[...page.items,...v]);setCursor(page.nextCursor??'')}catch(e){setError((e as Error).message)}}
 return <Dialog.Root open={open} onOpenChange={setOpen}>
 <Dialog.Trigger asChild><button className="agent-fab" aria-label="打开情报 Agent"><Sparkles size={20}/><span>情报 Agent<small>随时查证 · 随时起草</small></span><i/></button></Dialog.Trigger>
 <Dialog.Portal><Dialog.Overlay className="agent-overlay"/><Dialog.Content className="agent-panel">
 <header className="agent-header"><span className="agent-logo"><Sparkles size={20}/></span><div><Dialog.Title>情报 Agent</Dialog.Title><Dialog.Description>连接消息与背景，让每次表达都有依据</Dialog.Description></div><Dialog.Close asChild><button className="icon" aria-label="关闭 Agent"><X size={18}/></button></Dialog.Close></header>
 <div className="agent-toolbar"><span><Radio size={13}/>{status.data?.configured?'AI 已接入':'情报检索可用 · AI 待配置'}</span><button onClick={()=>setHistory(!history)} aria-label="会话历史"><History size={15}/></button><button onClick={()=>select('')} aria-label="新建 Agent 会话"><Plus size={17}/></button></div>
 {history?<div className="agent-history"><h3>最近会话</h3>{sessions.isPending&&<p>正在读取…</p>}{sessions.isError&&<p role="alert">历史暂时不可用</p>}{sessions.data?.length===0&&<p>尚无会话，开始查询最新情报。</p>}{sessions.data?.map(s=><button key={s.id} onClick={()=>select(s.id)}><b>{s.title}</b><small>{time(s.updatedAt)}</small></button>)}</div>:<div className="agent-messages" aria-live="polite">
 {!rows.length&&<div className="agent-welcome"><span className="agent-kicker">SIGNAL → CONTEXT → DRAFT</span><h3>今天，哪些消息<br/>值得你关注？</h3><p>从全球新闻、加密、宏观与科技来源中寻找线索。每条解读都保留时间与出处。</p><div className="agent-suggestions"><button disabled={busy||!!current} onClick={()=>void send('latest','最新情报')}>最新情报 <ArrowUpRight size={15}/></button><button disabled={busy||!!current} onClick={()=>void send('refresh','刷新已批准来源')}>刷新来源 <ArrowUpRight size={15}/></button><button disabled={busy||!!current||!attach||!event} onClick={()=>void send('analyse','分析当前事件')}>分析当前事件 <ArrowUpRight size={15}/></button><button onClick={()=>setPrompt('bitcoin ETF')}>追踪主题 <ArrowUpRight size={15}/></button></div></div>}
 {(cursor===null?messages.data?.nextCursor:cursor)&&<button className="agent-older" onClick={()=>void loadOlder()}>加载更早消息</button>}
 {messages.isError&&<p role="alert">连接中断，重新打开面板可恢复记录。</p>}
 {rows.map(m=>{let a:Answer={};try{a=JSON.parse(m.result)}catch{}return <section className="agent-turn" key={m.id}><div className="agent-user"><small>{time(m.createdAt)}</small><p>{m.prompt||'最新情报'}</p></div><div className="agent-response"><div className="agent-response-label"><Sparkles size={14}/> SIGNAL ATLAS <span>{m.status==='completed'?'已完成':m.progress}</span></div>{m.status==='completed'?<><p className="agent-summary">{a.summary}</p>{([['来源声明的事实',a.facts],['媒体报道',a.reports],['预测 · 条件性判断',a.predictions],['市场传闻',a.rumors],['不确定性',a.uncertainties]] as const).map(([label,list])=>list?.length?<div className="agent-claims" key={label}><b>{label}</b><ul>{list.map((v,i)=><li key={i}>{v}</li>)}</ul></div>:null)}{a.draft&&<div className="agent-draft"><b>候选草稿 · 待人工审核</b><p>{a.draft}</p>{a.draftId&&<button onClick={()=>{onDraft();setOpen(false)}}>前往发布中心 <ArrowUpRight size={14}/></button>}</div>}{!!a.sources?.length&&<details className="agent-sources"><summary>{a.sources.length} 条来源 · 查看时间与出处</summary>{a.sources.map(s=><article key={s.id}><a href={/^https?:\/\//i.test(s.url)?s.url:undefined} target="_blank" rel="noreferrer">{s.title}<ArrowUpRight size={12}/></a><small>{s.source}<br/>发布 {time(s.publishedAt)}<br/>采集 {time(s.collectedAt)}</small></article>)}</details>}<small className="agent-asof">数据截至 {time(a.asOf)}{m.model?' · '+m.model:''}</small></>:<p className={m.status==='failed'?'agent-error':'agent-task-state'}>{m.progress}</p>}</div></section>})}<div ref={bottom}/></div>}
 <footer className="agent-footer">{connected&&<ModelPicker label="本次 Agent 模型" value={model} onChange={setModel} disabled={busy||!!current}/>}<nav className="agent-quick" aria-label="Agent 快捷操作"><button disabled={busy||!!current} onClick={()=>void send('latest','最新情报')}>最新情报</button><button disabled={busy||!!current} onClick={()=>void send('refresh','刷新已批准来源')}>刷新来源</button><button disabled={busy||!!current||!attach||!event} onClick={()=>void send('analyse','分析当前事件')}>分析事件</button></nav>{event&&<label className="agent-context"><input type="checkbox" checked={attach} onChange={e=>setAttach(e.target.checked)}/><span>附带当前事件：{event.title}</span></label>}{error&&<p className="agent-error" role="alert">{error}</p>}
 {!connected?<button className="primary" onClick={()=>{setOpen(false);onLogin()}}>连接工作空间后使用</button>:<form onSubmit={e=>{e.preventDefault();if(prompt.trim())void send('search')}}><textarea aria-label="Agent 问题" placeholder="输入主题、关键词或对当前事件的提问…" maxLength={4000} value={prompt} onChange={e=>setPrompt(e.target.value)} onKeyDown={e=>{if(e.key==='Enter'&&!e.shiftKey&&!e.nativeEvent.isComposing){e.preventDefault();if(prompt.trim())void send('search')}}}/><div className="agent-compose-actions"><button type="button" disabled={busy||!!current||(!prompt.trim()&&!attach)} onClick={()=>void send('draft')}>生成待审核草稿</button>{current?<button type="button" className="agent-stop" onClick={()=>void cancel()}><Square size={12}/>停止任务</button>:<button type="submit" className="agent-send" disabled={busy||!prompt.trim()} aria-label="发送 Agent 问题"><ArrowUp size={17}/></button>}</div></form>}
 <small className="agent-boundary">仅查询、分析和起草 · 发布需要人工审核{status.data?' · 今日 '+status.data.used+'/'+status.data.dailyLimit:''}</small></footer>
 </Dialog.Content></Dialog.Portal></Dialog.Root>
}
